import { getOpportunities } from "@/lib/data/app-data";
import { StatusPill } from "@/components/app/status-pill";

function tone(readiness: string) { return readiness === "Ready now" ? "success" as const : readiness === "Build toward" ? "warning" as const : "neutral" as const; }

export default async function OpportunitiesPage() {
  const live = await getOpportunities();
  return <div className="app-page"><section className="page-heading"><span className="eyebrow">EXPLAINED MATCHES</span><h1>Opportunities without fake certainty.</h1><p>Every card shows what your evidence supports, what is missing, and what Lan Pya cannot know.</p></section><div className="filter-row"><button className="filter-chip active">All</button><button className="filter-chip">Internships</button><button className="filter-chip">Challenges</button><button className="filter-chip">Scholarships</button></div>{live.length ? <div className="opportunity-list">{live.map((item) => <article className="panel opportunity-card" key={item.id}><div className="opportunity-header"><div><span className="eyebrow">{item.type} · {item.location}</span><h2>{item.title}</h2><p>{item.organization}</p></div><StatusPill tone={tone(item.readiness)}>{item.readiness}</StatusPill></div><div className="readiness-grid"><div><strong>Supported by your proof</strong>{item.supported.length ? <ul>{item.supported.map((value) => <li key={value}>{value}</li>)}</ul> : <p>Nothing verified yet.</p>}</div><div><strong>Gaps to close</strong>{item.gaps.length ? <ul>{item.gaps.map((value) => <li key={value}>{value}</li>)}</ul> : <p>No known evidence gap.</p>}</div><div><strong>Still unknown</strong>{item.unknown.length ? <ul>{item.unknown.map((value) => <li key={value}>{value}</li>)}</ul> : <p>No declared unknowns.</p>}</div></div><footer><span>Deadline: {item.deadline} · checked {new Date(item.lastVerifiedAt).toLocaleDateString()}</span><a className="button outline compact" href={item.sourceUrl} target="_blank" rel="noreferrer">Open source ↗</a></footer></article>)}</div> : <section className="panel empty-state"><h2>No live opportunities yet.</h2><p>Partner-verified listings will appear here as they are published.</p></section>}</div>;
}
