import { getOpportunities } from "@/lib/data/app-data";
import { StatusPill } from "@/components/app/status-pill";
import { formatAppDate, getAppCopy } from "@/lib/i18n/app-copy";

function tone(readiness: string) { return readiness === "Ready now" ? "success" as const : readiness === "Build toward" ? "warning" as const : "neutral" as const; }

export default async function OpportunitiesPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const c = getAppCopy(locale);
  const live = await getOpportunities();
  return <div className="app-page"><section className="page-heading"><span className="eyebrow">{c.opportunities.heading}</span><h1>{c.opportunities.title}</h1><p>{c.opportunities.body}</p></section><div className="filter-row"><button className="filter-chip active">{c.opportunities.all}</button><button className="filter-chip">{c.opportunities.internships}</button><button className="filter-chip">{c.opportunities.challenges}</button><button className="filter-chip">{c.opportunities.scholarships}</button></div>{live.length ? <div className="opportunity-list">{live.map((item) => <article className="panel opportunity-card" key={item.id}><div className="opportunity-header"><div><span className="eyebrow">{item.type} · {item.location}</span><h2>{item.title}</h2><p>{item.organization}</p></div><StatusPill tone={tone(item.readiness)}>{item.readiness}</StatusPill></div><div className="readiness-grid"><div><strong>{c.opportunities.supported}</strong>{item.supported.length ? <ul>{item.supported.map((value) => <li key={value}>{value}</li>)}</ul> : <p>{c.opportunities.noneVerified}</p>}</div><div><strong>{c.opportunities.gaps}</strong>{item.gaps.length ? <ul>{item.gaps.map((value) => <li key={value}>{value}</li>)}</ul> : <p>{c.opportunities.noGaps}</p>}</div><div><strong>{c.opportunities.unknown}</strong>{item.unknown.length ? <ul>{item.unknown.map((value) => <li key={value}>{value}</li>)}</ul> : <p>{c.opportunities.noUnknowns}</p>}</div></div><footer><span>{c.opportunities.deadline}: {item.deadline} · {c.opportunities.checked} {formatAppDate(locale, item.lastVerifiedAt)}</span><a className="button outline compact" href={item.sourceUrl} target="_blank" rel="noreferrer">{c.opportunities.open} ↗</a></footer></article>)}</div> : <section className="panel empty-state"><h2>{c.opportunities.emptyTitle}</h2><p>{c.opportunities.emptyBody}</p></section>}</div>;
}
