import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { getAdminSummary, getRoles } from "@/lib/data/app-data";

export default async function AdminPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; const user = await requireUser(locale); const roles = await getRoles(user.id); if (!roles.has("admin")) notFound();
  const summary = await getAdminSummary();
  const my = locale === "my";
  return <div className="app-page"><section className="page-heading"><span className="eyebrow">{my ? "လုပ်ငန်းလည်ပတ်မှု ထိန်းချုပ်မှု" : "OPERATIONAL CONTROL"}</span><h1>{my ? "Trust system အခြေအနေ။" : "Trust system health."}</h1><p>{my ? "Live metrics များတွင် seeded demonstration ကို ဖယ်ထုတ်ပြီး စနစ် feedback နှင့် လူသားအတည်ပြုမှုကို သီးခြားပြထားသည်။" : "Live metrics exclude seeded demonstrations and separate automated feedback from human verification."}</p></section><section className="metric-grid"><article><span>{my ? "Review backlog" : "Review backlog"}</span><strong>{String(summary.review_backlog ?? 0)}</strong><small>{my ? "Live တင်သွင်းချက်များသာ" : "Live submissions only"}</small></article><article><span>{my ? "Review အလယ်အလတ် ကြာချိန်" : "Median review age"}</span><strong>{String(summary.median_review_hours ?? 0)}h</strong><small>{my ? "လူသားစစ်ဆေးမှုစာရင်း" : "Human queue"}</small></article><article><span>{my ? "အတည်ပြုပြီး သက်သေ" : "Verified proof"}</span><strong>{String(summary.verified_live ?? 0)}</strong><small>{my ? "လူသားအတည်ပြုထားသော live record များ" : "Human-verified live records"}</small></article></section><div className="admin-grid"><section className="panel"><h2>{my ? "Reviewer ဖိတ်ခေါ်ပါ" : "Invite a reviewer"}</h2><form action="/api/admin/invites" method="post" className="stack-form"><label>{my ? "အီးမေးလ်" : "Email"}<input type="email" name="email" required /></label><label>{my ? "အခန်းကဏ္ဍ" : "Role"}<select name="role"><option value="reviewer">{my ? "Reviewer" : "Reviewer"}</option><option value="reviewer_lead">{my ? "Reviewer ဦးဆောင်သူ" : "Reviewer lead"}</option></select></label><button className="button primary">{my ? "ဖိတ်ခေါ်မှု ဖန်တီးပါ" : "Create invite"}</button></form></section><section className="panel"><h2>{my ? "အခွင့်အလမ်း စာရင်းသွင်းခြင်း" : "Opportunity intake"}</h2><form action="/api/admin/opportunities" method="post" className="stack-form"><label>{my ? "ခေါင်းစဉ်" : "Title"}<input name="title" required /></label><label>{my ? "အဖွဲ့အစည်း" : "Organization"}<input name="organization" required /></label><label>{my ? "မူရင်း URL" : "Source URL"}<input type="url" name="sourceUrl" required /></label><button className="button gold">{my ? "Draft listing သိမ်းပါ" : "Save draft listing"}</button></form></section></div></div>;
}
