import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { getAdminSummary, getRoles } from "@/lib/data/app-data";

export default async function AdminPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; const user = await requireUser(locale); const roles = await getRoles(user.id); if (!roles.has("admin")) notFound();
  const summary = await getAdminSummary();
  return <div className="app-page"><section className="page-heading"><span className="eyebrow">OPERATIONAL CONTROL</span><h1>Trust system health.</h1><p>Live metrics exclude seeded demonstrations and separate automated feedback from human verification.</p></section><section className="metric-grid"><article><span>Review backlog</span><strong>{String(summary.review_backlog ?? 0)}</strong><small>Live submissions only</small></article><article><span>Median review age</span><strong>{String(summary.median_review_hours ?? 0)}h</strong><small>Human queue</small></article><article><span>Verified proof</span><strong>{String(summary.verified_live ?? 0)}</strong><small>Human-verified live records</small></article></section><div className="admin-grid"><section className="panel"><h2>Invite a reviewer</h2><form action="/api/admin/invites" method="post" className="stack-form"><label>Email<input type="email" name="email" required /></label><label>Role<select name="role"><option value="reviewer">Reviewer</option><option value="reviewer_lead">Reviewer lead</option></select></label><button className="button primary">Create invite</button></form></section><section className="panel"><h2>Opportunity intake</h2><form action="/api/admin/opportunities" method="post" className="stack-form"><label>Title<input name="title" required /></label><label>Organization<input name="organization" required /></label><label>Source URL<input type="url" name="sourceUrl" required /></label><button className="button gold">Save draft listing</button></form></section></div></div>;
}
