import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { SubmissionForm } from "@/components/missions/submission-form";
import { getActivePathDashboard } from "@/lib/data/app-data";
import { getAppCopy } from "@/lib/i18n/app-copy";

export default async function MissionPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const user = await requireUser(locale);
  const c = getAppCopy(locale).mission;
  const my = locale === "my";
  const dashboard = await getActivePathDashboard();
  if (dashboard.activePath?.key !== "frontend-developer") redirect(`/${locale}/app/build`);
  return <div className="app-page"><section className="page-heading"><span className="eyebrow">{my ? "MILESTONE 3 · လိုအပ်သော သက်သေ" : "MILESTONE 3 · REQUIRED PROOF"}</span><h1>{c.frontendTitle}</h1><p>{my ? "သေးငယ်သော interface တစ်ခုကို content၊ keyboard navigation နှင့် 320px အထက် screen များတွင် မှန်ကန်စွာ လုပ်ဆောင်နိုင်အောင် တည်ဆောက်ပါ။" : "Make a small interface withstand real constraints: content, keyboard navigation, and screens from 320px upward."}</p></section><div className="mission-layout"><section className="panel mission-brief"><div className="brief-tag">{my ? "MISSION BRIEF · v1" : "MISSION BRIEF · v1"}</div><h2>{my ? "တကယ့်သင်ယူသူအတွက် တည်ဆောက်ပါ။" : "Build for a real learner."}</h2><p>{my ? "အမည်၊ သင်ယူရည်မှန်းချက်၊ လက်ရှိ skill များနှင့် ရှင်းလင်းသော action တစ်ခုပါသော profile card တည်ဆောက်ပါ။ Core experience အတွက် HTML နှင့် CSS ကိုသာ သုံးပါ။" : "Create a profile card with a name, learning goal, current skills, and one clear action. Use only HTML and CSS for the core experience."}</p><h3>{my ? "လက်ခံမှုစံနှုန်းများ" : "Acceptance criteria"}</h3><ul className="rubric-list"><li><b>30%</b><span><strong>{my ? "Semantic structure" : "Semantic structure"}</strong><small>{my ? "Heading၊ list နှင့် control များက အဓိပ္ပာယ်ကို ရှင်းလင်းစွာ ဖော်ပြရမည်။" : "Headings, lists, and controls convey meaning."}</small></span></li><li><b>30%</b><span><strong>{my ? "Responsive behavior" : "Responsive behavior"}</strong><small>{my ? "320px တွင် clipping သို့မဟုတ် horizontal scroll မရှိရ။" : "No clipping or horizontal scroll at 320px."}</small></span></li><li><b>25%</b><span><strong>{my ? "အသုံးပြုရလွယ်ကူသော interaction" : "Accessible interaction"}</strong><small>{my ? "Keyboard focus၊ contrast နှင့် ဖတ်ရှုရလွယ်ကူသော label များပါရမည်။" : "Keyboard focus, contrast, and readable labels."}</small></span></li><li><b>15%</b><span><strong>{my ? "ရှင်းလင်းချက်" : "Explanation"}</strong><small>{my ? "Reflection က ရွေးချယ်မှုများနှင့် ရလဒ်များကို ချိတ်ဆက်ရမည်။" : "Reflection connects choices to outcomes."}</small></span></li></ul><div className="mission-guardrail"><strong>{my ? "Ground-truth စည်းမျဉ်း" : "Ground-truth rule"}</strong><p>{my ? "Automated scan အောင်မြင်ရုံဖြင့် မလုံလောက်ပါ။ Reviewer က render လုပ်ထားသော ရလဒ်နှင့် သင့်ရှင်းလင်းချက်ကို စစ်ဆေးမည်။" : "A passing automated scan is never enough. A reviewer checks the rendered result and your explanation."}</p></div></section><SubmissionForm locale={locale} userId={user.id} title={c.projectEvidence} /></div></div>;
}
